language: node_js
node_js:
  - 14

services:
  - docker

script:
  - docker build -t udagram-frontend .
  - docker tag udagram-frontend manhvuduc/udagram-frontend:v1

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push manhvuduc/udagram-frontend:v1
